version: "3"  

tasks:  
  default:
    cmds:  
      - task: generate  
  generate:  
    aliases:
      - gen  
    desc: "Generate code from proto files"  
    cmds:  
      - protoc -I proto proto/auth.proto --go_out=./gen/auth/ --go_opt=paths=source_relative --go-grpc_out=./gen/auth/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/apiToken.proto --go_out=./gen/apiToken/ --go_opt=paths=source_relative --go-grpc_out=./gen/apiToken/ --go-grpc_opt=paths=source_relative
      - protoc -I proto proto/video.proto --go_out=./gen/video/ --go_opt=paths=source_relative --go-grpc_out=./gen/video/ --go-grpc_opt=paths=source_relative